sudo mysql -u root -p
123456

CREATE DATABASE  itu_cantine;
CREATE USER 'admin_itu_cantine'@'localhost' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON itu_cantine.* TO 'admin_itu_cantine'@'localhost';

mysql -u admin_itu_cantine itu_cantine -p
123456

CREATE TABLE PLAT(
    CODEPLAT INT(3) NOT NULL AUTO_INCREMENT,
    INTITULE VARCHAR(100) NOT NULL,
    PRIX DECIMAL(10, 2) NOT NULL,
    DEVISE VARCHAR(2) NOT NULL,
    PRIMARY KEY (CODEPLAT)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE MENU(
    DATEMENU TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CODEPLAT INT(3) NOT NULL,
    FOREIGN KEY (CODEPLAT) REFERENCES PLAT(CODEPLAT)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX UK_MENU ON MENU (DATEMENU, CODEPLAT);

CREATE TABLE ETUDIANT(
    NUMETU VARCHAR(10) NOT NULL,
    MOTDEPASSE VARCHAR(40) NOT NULL,
    NOM VARCHAR(150) NOT NULL,
    DATENAISSANCE TIMESTAMP NOT NULL,
    PRIMARY KEY (NUMETU)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX UK_ETUDIANT ON ETUDIANT (NUMETU, NOM, DATENAISSANCE);

CREATE TABLE CONNEXION(
    NUMETU VARCHAR(10) NOT NULL,
    TOKEN VARCHAR(40) NOT NULL,
    FOREIGN KEY (NUMETU) REFERENCES ETUDIANT(NUMETU)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX UK_CONNEXION ON CONNEXION (NUMETU);

CREATE TABLE COMMANDE(
    IDCOMMANDE INT(3) NOT NULL AUTO_INCREMENT,
    DATECOMMANDE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NUMETU VARCHAR(10) NOT NULL,
    CODEPLAT INT(3) NOT NULL,
    NOMBRE INT NOT NULL,
    PRIMARY KEY(IDCOMMANDE),
    FOREIGN KEY (NUMETU) REFERENCES ETUDIANT(NUMETU),
    FOREIGN KEY (CODEPLAT) REFERENCES PLAT(CODEPLAT)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO PLAT (INTITULE, PRIX, DEVISE) VALUES
('Hena Kisoa sy Ravitoto', 4000, 'Ar'),
("Trondro Sauce", 5000, 'Ar'),
('Akoho Sauce', 4500, 'Ar'),
('Sosisy sy Tsaramaso', 3000, 'Ar'),
('Anandrano sy Sosisy', 3500, 'Ar');

INSERT INTO MENU (DATEMENU, CODEPLAT) VALUES
(STR_TO_DATE('6-1-2021', '%d-%m-%Y'), 1),
(STR_TO_DATE('6-1-2021', '%d-%m-%Y'), 2),
(STR_TO_DATE('6-1-2021', '%d-%m-%Y'), 3),
(STR_TO_DATE('6-1-2021', '%d-%m-%Y'), 4),
(STR_TO_DATE('7-1-2021', '%d-%m-%Y'), 1),
(STR_TO_DATE('7-1-2021', '%d-%m-%Y'), 3),
(STR_TO_DATE('7-1-2021', '%d-%m-%Y'), 4),
(STR_TO_DATE('7-1-2021', '%d-%m-%Y'), 5);

INSERT INTO ETUDIANT (NUMETU, MOTDEPASSE, NOM, DATENAISSANCE) VALUES ('ETU000937', 'coucou', 'Sombiniaina', STR_TO_DATE('20-12-2000', '%d-%m-%Y')), VALUES ('ETU001058', 'lavabe', 'Andry', STR_TO_DATE('30-7-2000', '%d-%m-%Y'));

INSERT INTO COMMANDE (NUMETU, CODEPLAT, NOMBRE) VALUES ('ETU000937', 1, 2), ('ETU000937', 4, 1), ('ETU001058', 2, 1);

-- 1
CREATE OR REPLACE VIEW MENUDUJOUR AS SELECT * FROM PLAT NATURAL JOIN MENU WHERE DATE(DATEMENU) = DATE(CURRENT_TIMESTAMP);

CREATE OR REPLACE VIEW ADDITION AS SELECT NUMETU, SUM(PRIX * NOMBRE) AS TOTAL, MAX(DEVISE) AS DEVISE FROM COMMANDE NATURAL JOIN PLAT WHERE DATE(DATECOMMANDE) = DATE(CURRENT_TIMESTAMP) GROUP BY NUMETU;

CREATE OR REPLACE VIEW COMMANDEDUJOUR AS SELECT CODEPLAT, INTITULE , SUM(NOMBRE) AS NOMBRE FROM COMMANDE NATURAL JOIN PLAT WHERE DATE(DATECOMMANDE) = DATE(CURRENT_TIMESTAMP) GROUP BY CODEPLAT, INTITULE;
